version: '3'

tasks:
  init:
    desc: "Terraform init"
    cmds:
      -  docker-compose -f docker-compose.yml run --rm terraform init

  plan:
    desc: "Terraform init"
    cmds:
      - docker-compose -f docker-compose.yml run --rm terraform plan


  apply:
    desc: "Terraform init"
    cmds:
      - docker-compose -f docker-compose.yml run --rm terraform apply

  destroy:
    desc: "Terraform init"
    cmds:
      - docker-compose -f docker-compose.yml run --rm terraform destroy
